<a href="https://colab.research.google.com/github/zhangyingchengqi/Modern-Computer-Vision-with-PyTorch/blob/master/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 练习一: pytorch安装,cuda启用，及张量创建

In [1]:
#验证pytorch是否安装成功:  python和pytorch在colab中默认安装好了
import torch
print(torch.__version__)
# 查看pytorch中的详情, True 表示成功启用 GPU
print(torch.cuda.is_available())
# 确定你的 CUDA 版本
!nvcc --version


2.6.0+cu124
True
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0


In [2]:
!python -c "import torch; print(torch.__version__); print(torch.version.cuda); print(torch.cuda.is_available())"
!nvidia-smi


2.6.0+cu124
12.4
True
Thu Aug  7 03:48:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   66C    P8             11W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-------------------------

In [3]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [4]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [5]:
#类型强制转为最为通用的类型
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [6]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[5, 5, 1, 1],
        [4, 1, 1, 6],
        [9, 3, 8, 4]])

In [10]:
torch.rand(3, 4) #0-1间的随机数的3行4列

tensor([[0.6495, 0.3721, 0.0255, 0.0044],
        [0.9924, 0.6303, 0.1253, 0.5954],
        [0.6854, 0.7857, 0.0093, 0.9195]])

In [11]:
torch.randn((3,4)) #符合正态分布的三行四列

tensor([[-0.1913, -0.2662, -0.0960,  0.3557],
        [ 0.7416,  1.4846, -1.9334,  1.2545],
        [ 1.5333, -0.5123, -1.1460, -0.0586]])

In [12]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)    # 直接将numpy数组转为张量
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [13]:
# 设置设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 创建两个张量并转移到 GPU
a = torch.rand(3, 3).to(device)
b = torch.rand(3, 3).to(device)
a,b

(tensor([[0.8188, 0.0276, 0.6029],
         [0.7789, 0.3665, 0.3946],
         [0.5333, 0.3892, 0.0802]], device='cuda:0'),
 tensor([[0.9328, 0.9222, 0.5353],
         [0.0819, 0.4807, 0.2771],
         [0.6522, 0.1559, 0.8032]], device='cuda:0'))