<a href="https://colab.research.google.com/github/zhangyingchengqi/Modern-Computer-Vision-with-PyTorch/blob/master/Chapter02/Specifying_batch_size_while_training_a_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第二章 第六节 batch size的调整测试

1. 什么是batch size?

在深度学习训练时，我们通常不会一次性把所有训练数据送进神经网络，而是**按批次（batch）**分成小块依次输入模型。

  * Batch Size = 每个批次里样本的数量

2. 为什么要用批量（Batch）？
  * 显存限制: 一次性输入太多数据会爆显存
  * 加速训练: 多个样本并行计算比逐个计算快
  * 梯度稳定性: Batch 的平均梯度比单样本梯度更稳定，训练更平滑
3. Batch Size 的取值?
  2 的幂次方（例如 16, 32, 64, 128, 256）: 因为 GPU 计算在 2 的幂时更高效
  * 太小（如 1~4） → 梯度波动大，训练慢
  * 太大（如 1024~8192） → 需要大量显存，可能欠拟合

In [1]:
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

In [2]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

In [3]:
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device)

In [5]:
class MyDataset(Dataset):
    def __init__(self,x,y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()
    def __len__(self):
        return len(self.x)
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]
ds = MyDataset(X, Y)

/tmp/ipython-input-1110550737.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x).float()
/tmp/ipython-input-1110550737.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y).float()


In [6]:
dl = DataLoader(ds, batch_size=2, shuffle=True) #创建一个 数据加载器（DataLoader） 的，它的作用是帮你**按批次（batch）和顺序（是否打乱）**把数据集 ds 喂给模型

In [8]:
# 临时性测试一下上面的dl
for xb, yb in dl:
    print(xb, yb)  # xb 是批次的输入数据，yb 是批次的标签
# 把数据集 ds 按批次大小 2 切分，每个 epoch 前随机打乱顺序，然后让你可以一个 batch 一个 batch 地取出来训练

tensor([[1., 2.],
        [7., 8.]], device='cuda:0') tensor([[ 3.],
        [15.]], device='cuda:0')
tensor([[5., 6.],
        [3., 4.]], device='cuda:0') tensor([[11.],
        [ 7.]], device='cuda:0')


In [13]:
class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # 定义输入层到隐藏层的线性变换：
        # 输入特征数为 2，隐藏层神经元数为 8
        self.input_to_hidden_layer = nn.Linear(2,8)
        # 定义隐藏层的激活函数为 ReLU（Rectified Linear Unit）
        # 用来引入非线性，使模型可以学习复杂关系
        self.hidden_layer_activation = nn.ReLU()
         # 定义隐藏层到输出层的线性变换：
        # 隐藏层神经元数为 8，输出层神经元数为 1
        self.hidden_to_output_layer = nn.Linear(8,1)
    #前向传播
    def forward(self, x):
        x = self.input_to_hidden_layer(x) # 1. 输入数据经过输入层到隐藏层的线性变换
        x = self.hidden_layer_activation(x)  # 2. 对隐藏层的输出应用激活函数 ReLU
        x = self.hidden_to_output_layer(x)  # 3. 隐藏层输出经过隐藏层到输出层的线性变换
        return x

In [15]:
mynet = MyNeuralNet().to(device) # 创建神经网络实例，并将其放到指定的计算设备（CPU 或 GPU）上
loss_func = nn.MSELoss()  #损失函数 均方误差损失
from torch.optim import SGD
opt = SGD(mynet.parameters(), lr = 0.001)  #优化器, 学习率为 0.001   mynet.parameters() 会返回网络中所有需要优化的参数（权重和偏置）

In [16]:
import time
loss_history = []  # 用于记录每次训练迭代的损失值
start = time.time()  # 记录训练开始的时间
# 外层循环：重复整个数据集的训练 50 次（50 个 epoch）
for _ in range(50):
    # 内层循环：从 DataLoader (dl) 中按批次读取数据
    # data 是一个批次的数据，通常是 (特征张量 x, 标签张量 y)
    for data in dl:
        x, y = data  # 将批次中的输入数据和标签解包到变量 x, y
        # 1. 将优化器中保存的上一次梯度清零
        # （否则梯度会累加，影响计算）
        opt.zero_grad()
        # 2. 前向传播：将输入 x 传入网络 mynet，得到预测值
        # 3. 计算损失值 loss_value：预测值与真实标签 y 的误差
        loss_value = loss_func(mynet(x), y)
        # 4. 反向传播：计算每个参数的梯度
        loss_value.backward()
        # 5. 优化器更新参数（使用计算出来的梯度）
        opt.step()
        # 6. 记录本批次的损失值（可用于后续画损失曲线）
        loss_history.append(loss_value)
end = time.time()  # 记录训练结束的时间
# 打印整个训练过程耗时
print(end - start)


0.4657168388366699


In [17]:
#下面预测新的数据点的输出值
val_x = [[10,11]]

In [18]:
val_x = torch.tensor(val_x).float().to(device)

In [19]:
mynet(val_x)

tensor([[20.4651]], device='cuda:0', grad_fn=<AddmmBackward0>)

下一节引入自定义的损失函数  Implementing_custom_loss_function